version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.7-stretch-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            npm install
            gem install percy-cli
            node -v
      - run:
          name: run our tests
          command: |
            npm run build
            percy snapshot public
